import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ico from '@/public/img.ico'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Convert SRT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
        <title>Convert SRT</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
